######################################################################
# Automatically generated by qmake (2.01a) Wed Apr 8 09:07:07 2020
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += prog.h
SOURCES += main.cpp prog.cpp
