######################################################################
# Automatically generated by qmake (2.01a) Tue Apr 7 15:16:53 2020
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += prog.h
SOURCES += main.cpp prog.cpp
